version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev
    volumes:
      - ./frontend:/app
    restart: unless-stopped
